version: "3.7"
services:
  #PHP Service
  website:
    build:
      context: .
      dockerfile: docker/environments/development/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      - NODE_ENV=development
    ports:
    - 3000
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    networks:
      - default
      - app-network

  nginx:
    image: nginx
    restart: unless-stopped
    working_dir: /etc/nginx
    env_file:
      - docker/environments/development/.docker.nginx.env
    ports:
      - 80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d


#Docker Networks
networks:
  app-network:
    driver: bridge
  default:
    external:
      name: nginx-proxy
