version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
#version: 2.1
#orbs:
#  node: circleci/node@2.0.2
#
#jobs:
#  build:
#    docker:
#      # Specify the version you desire here
#      - image: node:12.16.1-alpine
#      # Specify service dependencies here if necessary
#      # CircleCI maintains a library of pre-built images
#      # documented at https://circleci.com/docs/2.0/circleci-images/
#      # Using the RAM variation mitigates I/O contention
#      # for database intensive operations.
#      # - image: circleci/mysql:5.7-ram
#      #
#      # - image: redis:3
#
#
#    steps:
#      - checkout
#      # node cache
#      - restore_cache:
#          keys:
#            - node-v4-{{ checksum "package.json" }}
#            - node-v4-
#            - run: npm install
#      - save_cache:
#          key: node-v4-{{ checksum "package.json" }}
#          paths:
#            - node_modules
#            - ~/.yarn
#      - run: apk update && apk add openssh rsync #install openssh rsync on bitbucket machine
#      - run: npm install
#      - run: unset CI
#      - run: npm run-script build
#      - run: mkdir packaged
#workflows:
#  build-and-test:
#    jobs:
#      - build
